### ISSUE TITLE
EAS build --platform ios file size 5.6gb?

### ISSUE THREAD

**Issue by michaeljamieson10** [ivopr/tamagui-expo#19]
When running the eas build --platform ios file size my files get compressed to the size of 5.6gb and then I get 400 error (most likely due to the 4gb ios limit)  
Can you guys make a guide on how to use eas build with Tamagui? I have tried other Tamagui templates and it always ends up having a lot of file size after compression!

**Comment by michaeljamieson10** [comment]
i attempted to use eas build --platform ios from this template without any alterations

**Comment by michaeljamieson10** [comment]
Your project archive is 5.6 GB. You can reduce its size and the time it takes to upload by excluding files that are unnecessary for the build process in .easignore file. Learn more: https://expo.fyi/eas-build-archive
✖ Uploading to EAS Build (5.6 GB / 5.6 GB)
Error: Request failed: 400 (Bad Request)
    at default_1 (/usr/local/lib/node_modules/eas-cli/build/fetch.js:29:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadWithSignedUrlWithProgressAsync (/usr/local/lib/node_modules/eas-cli/build/uploads.js:85:26)
    at async uploadFileAtPathToGCSAsync (/usr/local/lib/node_modules/eas-cli/build/uploads.js:12:5)
    at async attemptEvent (/usr/local/lib/node_modules/eas-cli/build/build/build.js:147:31)
    at async withAnalyticsAsync (/usr/local/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async uploadProjectAsync (/usr/local/lib/node_modules/eas-cli/build/build/build.js:139:16)
    at async prepareBuildRequestForPlatformAsync (/usr/local/lib/node_modules/eas-cli/build/build/build.js:72:24)
    at async prepareIosBuildAsync (/usr/local/lib/node_modules/eas-cli/build/build/ios/build.js:58:12)

**Comment by ivopr** [comment]
@michaeljamieson10 hey, Sorry for the delay. unfortunately I'm unable to test and see what is happening, since I don't have anything apple-related. You could check If `node_modules` are being uploaded by adding a `.easignore` and putting `node_modules` in here. I'm Sorry that I'm unable to help you any further.

Edit: you can also try updating tamagui with `yarn upgrade:tamagui` since It's been some time since I did It. And as far as I remember, some time ago someone brought this up on tamagui discord, but I didn't read any further

**Comment by ivopr** [comment]
well, as there is no response I'll be closing this, feel free to reopen If needed
